### ISSUE TITLE
Generating decoded values

### ISSUE THREAD

**Issue by theisuru** [spiros/tofu#2]
Thanks for this great tool.
We are working on CINECA project and greatly benefit from this. For the project we are also interested in directly generating decoded values. I have made a fork and created a [branch](https://github.com/theisuru/tofu/tree/generate_decoded_values) for this feature. If you think this would benefit others, I can create a pull request. Let me know your thoughts or need more information.

**Comment by spiros** [comment]
Hey thanks for getting in touch!

I think this is a great idea plus I love the `--human` flag. I would be happy to merge this into the tool so please go ahead and submit a PR.

**Comment by spiros** [comment]
Thanks, merged d812be9f57a58380d30ec872449087af8da3ef6e :)
