### ISSUE TITLE
Add support for loading fields from file

### ISSUE THREAD

**Issue by alepev** [spiros/tofu#5]
I need to run `tofu` with specific subsets of fields to generate different synthetic test files, each with variables from a specific domain.
Passing the fields via command line is not always ideal if it's more than just a few, and it would be nice to capture how I generated the output in the first place, especially if I want to re-use these fields in a future run.
I think the solution is to enable a file option, preferably mutually exclusive with the current `-f` argument.

The file format I propose is the following:
- one field per line
- anything after the field on the same line will be ignored (for example, comments)
- empty lines and lines starting with `#` will be ignored
```bash
# my file - this line is a comment
51
32
# the empty line below is ignored

34 200 # the second number and this comment are ignored
```

**Comment by spiros** [comment]
Thank you, merged!
